export const PartGroupNames: { [key: string]: string } = {
  '11': 'Engine',
  '12': 'Engine electrical system',
  '13': 'Fuel preparation and control',
  '16': 'Fuel supply',
  '17': 'Cooling',
  '18': 'Exhaust system',
  '21': 'Clutch',
  '22': 'Engine and transmission mount',
  '23': 'Manual gearbox',
  '24': 'Automatic gearbox',
  '25': 'Gearshift',
  '26': 'Propeller shaft',
  '27': 'Transfer box / EV Transmission',
  '28': 'Twin-clutch gearbox (DKG)',
  '31': 'Front axle',
  '32': 'Steering',
  '33': 'Rear Axle',
  '34': 'Brake',
  '35': 'Foot controls',
  '36': 'Wheels',
  '37': 'Integrated suspension systems',
  '41': 'Bodyshell',
  '46': 'Frame and add-on parts',
  '51': 'Body equipment',
  '52': 'Seats',
  '54': 'Sliding / tilting sunroof and convertible top',
  '61': 'General vehicle electrical system',
  '62': 'Instruments, Measuring systems',
  '63': 'Lighting',
  '64': 'Heating and air conditioning',
  '65': 'Audio, navigation, information systems',
  '66': 'Distance systems, cruise control, remote key',
  '67': 'Electrical drives',
  '71': 'Equipment parts',
  '72': 'Restraint system and accessories, body',
  '84': 'Communication systems',
}
