[build]
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["axios","node-cryptojs-aes"]

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
