[build]
functions = "netlify/functions"
command = "npm run build"
publish = ".next"

[functions]
node_bundler = "esbuild"
external_node_modules = ["axios","node-cryptojs-aes"]

[[plugins]]
package = "@netlify/plugin-nextjs"
